import { FC } from 'react'
import Head from 'next/head'
import { GetServerSideProps, GetServerSidePropsResult } from 'next'
import SearchBar from '../components/SearchBar'
import Quotation, { IQuoteRes } from '../components/Quotation'
import BookMarks from '../components/BookMarks'
import axios from 'axios'

const Home: FC<{ data: IQuoteRes }> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Nav Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen max-w-full overflow-hidden px-4 pt-8 pb-4 md:p-10 md:flex md:flex-col md:items-start">
        <Quotation quote={data} />
        <div className="flex flex-col items-center w-full max-w-xl mx-auto">
          <SearchBar />
          <BookMarks />
        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps<{
  data: IQuoteRes
}> = async (): Promise<GetServerSidePropsResult<{ data: IQuoteRes }>> => {
  try {
    const QUOTA_API = 'https://apiv3.shanbay.com/weapps/dailyquote/quote/'
    const { data } = await axios.get<IQuoteRes>(QUOTA_API)
    return { props: { data } }
  } catch (e) {
    return { props: { data: {} } }
  }
}

export default Home
