import Head from 'next/head'
import SearchBar from '../components/SearchBar'
import Quotation from '../components/Quotation'
import BookMarks from '../components/BookMarks'

export default function Home() {
  return (
    <>
      <Head>
        <title>Nav Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen px-4 pt-8 pb-4 md:p-10 md:flex md:flex-col md:items-start">
        <div className="min-h-[12rem] md:min-h-[14rem]">
          <Quotation />
        </div>
        <div className="flex flex-col items-center w-full mt-4 max-w-xl mx-auto md:mt-2">
          <SearchBar />
          <BookMarks />
        </div>
      </main>
    </>
  )
}
